### ISSUE TITLE
About the preprocessing method on the cityscapes data

### ISSUE THREAD

**Issue by KevinChen880723** [shahaf1313/ProCST#1]
Hello, thanks for providing this fantastic method!

When tracing the code, I found a [comment](https://github.com/shahaf1313/ProCST/blob/main/data_handlers/cityscapes_dataset.py#L22) mentioning "use random crop, don't resize @ cityscapes," but the program resizes the image in the following snippets but doesn't random crop it. Is it just a typo? 

Thanks a lot!

**Comment by shahaf1313** [comment]
Hey Kevin, thanks for your comment!
You are right, in deed an old comment. I fixed the documentation to the current implementation.

Thanks,
Shahaf
