### ISSUE TITLE
There seems to be something wrong with your form.

### ISSUE THREAD

**Issue by Renp1ngs** [shahaf1313/ProCST#2]
Hello, Shahaf. 
Thanks for your wonderful work. But I have the following problem.

1. But it seems HRDA's mIoU on GTA->Cityscapes is 73.8, not 72.8.  What do you think caused the problem of different levels of improvement under different methods?  i.e. DAFormer+1.1, ProDA+0.6, HRDA+0.2
2. Have you ever done experiments with SiT on semi-supervised segmentation tasks?

Best regards,
Yanqi

**Comment by shahaf1313** [comment]
Hey Yanqi, thanks for your comments.
1. We have tested results on DAFormer and HRDA using our runs for fair comparison (hardware wise). Adittionally, we tested HRDA on 8 different seeds for robust comparison (original results were tested on 3 seeds).
2. Unfortuitnatlly, no.

**Comment by Renp1ngs** [comment]
Thanks for your quick reply.
> Adittionally, we tested HRDA on 8 different seeds for robust comparison (original results were tested on 3 seeds).

Solid work. Hope SiT can get into a good conference paper or journal paper.
