### ISSUE TITLE
TrainID of GTA5 

### ISSUE THREAD

**Issue by yangH8** [shahaf1313/ProCST#3]
How to convert the TrainID of GTA5 ?

**Comment by shahaf1313** [comment]
Hey Yang,
ProCST's translation process translates only images and preserve their content, thus no need to translate the labels.
Moreover, in the training process ProCST uses the original labels of GTA5, thus no need to convert them also before training.

**Comment by yangH8** [comment]
Thank you for your reply. How to translates the image?  Which program to run?

**Comment by shahaf1313** [comment]
Please refer to the README.md file for detailed information on both the training and evaluation (translation) of the model. The explanation covers all the prerequisites and describes what scripts you should use in each step.

**Comment by yangH8** [comment]
The translation of GTA5 images is not mentioned in README.md.

**Comment by shahaf1313** [comment]
Please refer to the "Boosting UDA Methods" section in the README.md file. In this section we describe how to translate images ("boost performance") from both GTA5 and Synthia datasets:
![image](https://user-images.githubusercontent.com/62223493/192316204-b4b058eb-07b3-420d-9b08-60c20fd71f67.png)

**Comment by yangH8** [comment]
Nice work! If I don't use boosting UDA methods, how can I process GTA5 datasets.  Just input raw images?

**Comment by yangH8** [comment]
we run the program in training.py. for batch_num, ((source_scales, source_label), target_scales) in enumerate(zip(opt.source_loaders[opt.curr_scale], opt.target_loaders[opt.curr_scale])):
RuntimeError: stack expects each tensor to be equal size, but got [127957, 1] at entry 0 and [127088, 1] at entry 1.

I have set the the same number of the input for source and target data

**Comment by shahaf1313** [comment]
You shouldn't run training.py. This file is wrapped with other scripts. If you want to train the model, refer to the "Train ProCST Model" section in the README file:
![image](https://user-images.githubusercontent.com/62223493/192441811-39efb418-a43c-4aac-ac08-43d56aff2602.png)
