### ISSUE TITLE
How can I label my dataset? Do I have to use the auto tool or do I have to do everything manually?

### ISSUE THREAD

**Issue by D-Mad** [shahaf1313/ProCST#5]

**Comment by shahaf1313** [comment]
Hey D-Mad,
In order to train your own dataset, you'll need to provide both a source dataloader and a target dataloader, and call them in train_procst.py. 
You can see examples of such dataloaders in the data_handlers/ directory.
Shahaf

**Comment by D-Mad** [comment]
Thank you, but I mean how to make label for src and target images, I have actual images and my game images, how can I make label for it.

**Comment by shahaf1313** [comment]
ProCST does not create labels. It translates the images from the source domain to mimic the images in the target domain (i.e. image translation) while preserving the semantic content. This preprocessing closes the gap between the domains and helps other UDA methods to enhance their performance.
Thus, if you wish to train a ProCST model to translate images from new datasets, you'll only need to create appropriate dataloaders as mentioned in the previous comment. Then you can use the trained model to create a translated (i.e. SiT) dataset, and use it to train any UDA method to enhance its performance.  
Shahaf
